// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/LocalMessage.h"
#include "EXLocalMessage.generated.h"

class USoundBase;

/**
 * 
 */
UCLASS(Blueprintable, Abstract, NotPlaceable, Meta = (ShowWorldContextPin))
class EX_API UEXLocalMessage : public ULocalMessage
{
	GENERATED_BODY()

public:

	// If true, put a GetString on the console.
	UPROPERTY(EditDefaultsOnly, Category = "Message")
	uint32 bIsConsoleMessage : 1;


	// # of seconds to stay in HUD message queue.
	UPROPERTY(EditDefaultsOnly, Category = Message)
	float Lifetime = 5.f;

	UPROPERTY(EditDefaultsOnly, Category = Message)
	float ScaleInSize = 1.f;

	/** 0=smallest font, 3=largest font. */
	UPROPERTY(EditDefaultsOnly, Category = Message)
	int32 FontSizeIndex = 1;


	void ClientReceive(const FClientReceiveData& ClientData) const override;

	UFUNCTION(BlueprintNativeEvent, BlueprintCallable, Category = "Message")
	FText ResolveMessage(int32 Switch = 0, bool bTargetsPlayerState1 = false, class APlayerState* RelatedPlayerState_1 = NULL, class APlayerState* RelatedPlayerState_2 = NULL, class UObject* OptionalObject = NULL) const;

	UFUNCTION(BlueprintImplementableEvent, Category = "Message")
	void OnClientReceive(APlayerController* LocalPC, int32 Switch, APlayerState* RelatedPlayerState_1, APlayerState* RelatedPlayerState_2, UObject* OptionalObject) const;

	/** Returns string to display on console for this message. */
	virtual FString GetConsoleString(const FClientReceiveData& ClientData, FText LocalMessageText) const;

	virtual bool IsConsoleMessage(int32 Switch) const;
	
	virtual FFormatNamedArguments GetArgs(int32 Switch, bool bTargetsPlayerState1, class APlayerState* RelatedPlayerState_1, class APlayerState* RelatedPlayerState_2, class UObject* OptionalObject) const;

	UFUNCTION(BlueprintCallable, BlueprintPure, Category = "Message")
	virtual FText GetText(int32 Switch = 0, bool bTargetsPlayerState1 = false, class APlayerState* RelatedPlayerState_1 = nullptr, class APlayerState* RelatedPlayerState_2 = nullptr, UObject* OptionalObject = nullptr) const;

	/**	Give Blueprints a way to override the text generated by this local message. */
	UFUNCTION(BlueprintNativeEvent, Category = "Message")
	FText Blueprint_GetText(int32 Switch, bool bTargetsPlayerState1, class APlayerState* RelatedPlayerState_1, class APlayerState* RelatedPlayerState_2, class UObject* OptionalObject) const;
	
	/** Return the name of announcement to play for this message (if any); UTAnnouncer will map to an actual sound */
	UFUNCTION(BlueprintNativeEvent, BlueprintCallable, BlueprintPure, Category = "Message")
	FName GetAnnouncementName(int32 Switch, const UObject* OptionalObject, const class APlayerState* RelatedPlayerState_1, const class APlayerState* RelatedPlayerState_2) const;

	/** Return the sound to play for the announcement, if GetAnnouncementName() returned NAME_Custom. */
	UFUNCTION(BlueprintNativeEvent, BlueprintCallable, BlueprintPure, Category = "Message")
	USoundBase* GetAnnouncementSound(int32 Switch, const UObject* OptionalObject) const;

	/** Initial Message scale */
	UFUNCTION(BlueprintNativeEvent, BlueprintCallable, BlueprintPure, Category = "Message")
	float GetScaleInSize(int32 MessageIndex) const;

	UFUNCTION(BlueprintCallable, BlueprintPure, Category = "Message")
	virtual float GetLifeTime(int32 Switch) const;

	/**	Give Blueprints a way to override the lifetime for this message */
	UFUNCTION(BlueprintNativeEvent, Category = "Message")
	float Blueprint_GetLifeTime(int32 Switch) const;

	/** Return color of displayed message. */
	UFUNCTION(BlueprintNativeEvent, BlueprintCallable, BlueprintPure, Category = "Message")
	FLinearColor GetMessageColor(int32 MessageIndex) const;

	virtual int32 GetFontSizeIndex(int32 MessageIndex, bool bTargetsLocalPlayer) const;

};
