// Fill out your copyright notice in the Description page of Project Settings.

#include "EX.h"
#include "Modules/ModuleManager.h"

IMPLEMENT_PRIMARY_GAME_MODULE( FDefaultGameModuleImpl, EX, "EX" );

DEFINE_LOG_CATEGORY(LogEXGameMode);
DEFINE_LOG_CATEGORY(LogEXGameState);
DEFINE_LOG_CATEGORY(LogEXChar);
DEFINE_LOG_CATEGORY(LogEXLevel);
DEFINE_LOG_CATEGORY(LogEXWeapon);
DEFINE_LOG_CATEGORY(LogEXAbility);
DEFINE_LOG_CATEGORY(LogEXInventory);
DEFINE_LOG_CATEGORY(LogEXController);
DEFINE_LOG_CATEGORY(LogEXObjective);
DEFINE_LOG_CATEGORY(LogEXAnim);
DEFINE_LOG_CATEGORY(LogEXTeam)
DEFINE_LOG_CATEGORY(LogEXAssaultCourse)
DEFINE_LOG_CATEGORY(LogEXUI)
DEFINE_LOG_CATEGORY(LogEXAdmin)
DEFINE_LOG_CATEGORY(LogEXBeacon)
DEFINE_LOG_CATEGORY(LogEXOnline)
DEFINE_LOG_CATEGORY(LogEXUIDebug)
DEFINE_LOG_CATEGORY(LogEXAssets)
DEFINE_LOG_CATEGORY(LogEXPlayer)

//For UE4 Profiler ~ Stat
DECLARE_CYCLE_STAT(TEXT("EX ~ STAT_StatTrack"), STAT_StatTrack, STATGROUP_EX);
